### ISSUE TITLE
refresh_time behavior

### ISSUE THREAD

**Issue by bablokb** [adafruit/Adafruit_CircuitPython_SPD1656#5]
I am trying to bring up Pimoroni's InkyFrame 5.7" display, which  has an integrated PicoW and uses an ACEP display. This driver works, but I experience some problems with the `refresh_time` behavior.

The board exposes the busy-pin of the display using a shift-register, so I cannot pass it as `busy_pin` (which expects a microcontroller.Pin). According to the documentation, displayio in this case waits `refresh_time` seconds after the refresh-command before it sends the stop-sequence.

My tests show that `display.refresh()` does wait (about) refresh_time seconds, but the actual refreshing takes place _afterwards_ (taking another 30 seconds). So setting e.g. `refresh_time=2` greatly speeds up the refresh-cycle, but I have to do the waiting myself.

Is this a misunderstanding on my side or a bug?

**Comment by tannewt** [comment]
I think this might be an artifact of the ACeP displays doing a "clean" refresh before the real refresh. I think the `refresh()` delay is the wait for the clean cycle. IIRC we usually try to return quickly from `refresh()` while the refresh happens but then error if another refresh happens too early.

**Comment by bablokb** [comment]
I already had a look at the code (EPaperDisplay.c) and wondered if it were possible to move down  `_clean_area()` a few lines to just _after_ the (next) start-refresh call, thus having only a single refresh. Does it make sense to try this?

BTW: Pimoroni does not do the cleaning at all in their driver-code.

I'm closing this issue here since it is not related to this driver.

**Comment by tannewt** [comment]
> I already had a look at the code (EPaperDisplay.c) and wondered if it were possible to move down `_clean_area()` a few lines to just _after_ the (next) start-refresh call, thus having only a single refresh. Does it make sense to try this?

If you want to try skipping the clean then simply comment it out. I didn't try it.
