### ISSUE TITLE
Convert `.show()` to `.root_group =` for CircuitPython 9

### ISSUE THREAD

**Issue by dhalbert** [adafruit/Adafruit_CircuitPython_SPD1656#6]
in examples and README.rst

**Comment by prcutler** [comment]
PR #7 updates the examples and README for both `display.root_group` and `fourwire.FourWire`, which was failing CI without the `fourwire` update.

The CI is still failing with a message: `/home/runner/work/Adafruit_CircuitPython_SPD1656/Adafruit_CircuitPython_SPD1656/adafruit_spd1656.py:docstring of adafruit_spd1656.SPD1656:15:'any' reference target not found: displayio.FourWire` but I can't find any other strings that match `displayio.FourWire`
